services:
  con:
    image: python
    volumes:
    - ./con/main.py:/main.py
    - ./db:${db_dir}:ro
    entrypoint: python -u /main.py -d ${db_dir} -n ${n} -b ${b}
    restart: always
    deploy:
      resources:
        limits:
          memory: 100M
  prod:
    image: python
    volumes:
    - ./prod/main.py:/main.py
    - ./db:${db_dir}
    entrypoint: python -u /main.py -d ${db_dir} -n ${n} -b ${b}
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 300M