services:
  con:
    image: python
    volumes:
    - ./con/main.py:/main.py
    - ./db:${db_dir}:ro
    - ./con/log.txt:/log.txt
    entrypoint: python -u /main.py -d ${db_dir} -n ${n} -b ${b}
    restart: always
    deploy:
      resources:
        limits:
          memory: 100M
  prod:
    image: python
    volumes:
    - ./prod/main.py:/main.py
    - ./db:${db_dir}
    - ./prod/log.txt:/log.txt
    entrypoint: python -u /main.py -d ${db_dir} -n ${n} -b ${b} -w ${w}
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 400M
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #   - 9090:9090
  #   command:
  #   - --config.file=/etc/prometheus/prometheus.yml
  #   volumes:
  #   - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   depends_on:
  #   - cadvisor
  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor
  #   ports:
  #   - 8080:8080
  #   volumes:
  #   - /:/rootfs:ro
  #   - /var/run:/var/run:rw
  #   - /sys:/sys:ro
  #   - /var/lib/docker/:/var/lib/docker:ro
  #   - /dev:/dev:ro 